# Generated by Django 5.1.4 on 2024-12-12 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0002_remove_deck_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='repeat_count',
            field=models.IntegerField(default=0),
        ),
    ]
